export interface Pemohon {
    PemohonId: string,
    Nama: string,
    Password: string,
    KodeVerifikasi: string,
    TglKodeVerifikasi: Date,
    Npwp: string,
    NpwpFileId: number,
    ContactPerson: string,
    Alamat: string,
    RefKotaId: number,
    Kota: string,
    KodePos: string,
    Email: string,
    Status: boolean,
    HasKodeVerifikasi: boolean,
    HasPassword: boolean,
    HasNpwpFile: boolean,
    Ereg: string,
}
